### ISSUE TITLE
Hello, can you provide the download address of the dataset?

### ISSUE THREAD

**Issue by 15779235038** [Demfier/philo#16]

**Comment by Demfier** [comment]
Hi @15779235038,

Here are the links for downloading the datasets used in this work:

1. [How2 dataset](https://github.com/srvk/how2-dataset#how2-download)
2. [Multi30K dataset](https://github.com/multi30k/dataset)
3. [IEMOCAP dataset](https://sail.usc.edu/iemocap/iemocap_release.htm)

Note that you'll need to fill a form for the How2 and the IEMOCAP datasets.

I am closing this issue, but feel free to open another one if you need to

Thanks,
Gaurav.
